version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - net

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - /data/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - net

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - /data/event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    networks:
      - net
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: koheiotsuka/dev:ananas_web
    restart: always
    command: sh -c "sleep 5 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env
    networks:
      - net

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - net
    depends_on:
      - plausible

networks:
  net:

volumes:
  geoip:
    driver: local
